#!/bin/bash

# Script de déploiement vers l'organisation Prohacktiv
echo "🚀 FlowUp Support Bot - Déploiement vers Prohacktiv"
echo "==================================================="

echo "📋 INSTRUCTIONS POUR DÉPLOYER VERS PROHACKTIV:"
echo ""
echo "1️⃣ CRÉER LE REPOSITORY SUR GITHUB:"
echo "   - Aller sur https://github.com/prohacktiv"
echo "   - Cliquer 'New repository'"
echo "   - Nom: flowup-support-bot"
echo "   - Description: FlowUp Support Bot avec détection UC_336"
echo "   - Public ou Private selon vos préférences"
echo "   - Ne pas initialiser avec README (le code existe déjà)"
echo ""
echo "2️⃣ CLONER ET CONFIGURER:"
echo "   git clone https://github.com/prohacktiv/flowup-support-bot.git"
echo "   cd flowup-support-bot"
echo "   git remote add source https://github.com/D4d0/kikoo_rag.git"
echo "   git pull source main"
echo "   git push origin main"
echo ""
echo "3️⃣ VÉRIFIER LE DÉPLOIEMENT:"
echo "   - Vérifier que tous les fichiers sont présents"
echo "   - Tester: python scripts/test_uc336_final.py"
echo "   - Vérifier la connectivité Odoo"
echo ""
echo "📊 FONCTIONNALITÉS DÉPLOYÉES:"
echo "  ✅ Détecteur UC_336 (100% précision)"
echo "  ✅ Réponses sécurisées (sans promesses)"
echo "  ✅ Escalade automatique"
echo "  ✅ Intégration Odoo"
echo "  ✅ Tests complets"
echo "  ✅ 838 tickets traités"
echo ""
echo "🔗 REPOSITORY SOURCE: https://github.com/D4d0/kikoo_rag"
echo "🎯 REPOSITORY CIBLE: https://github.com/prohacktiv/flowup-support-bot"
echo ""
echo "📋 FICHIERS PRINCIPAUX:"
echo "  - src/detectors/uc336_detector.py"
echo "  - src/templates/uc336_responses.py"
echo "  - src/core/enhanced_flowup_chatbot.py"
echo "  - tests/test_uc336.py"
echo "  - scripts/test_uc336_*.py"
echo "  - README_PROHACKTIV.md"
echo ""
echo "🚀 Le système est prêt pour Prohacktiv !"
